/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthVerifyGateRouteImport } from './routes/auth/verify-gate'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppCompaniesIndexRouteImport } from './routes/app/companies/index'
import { Route as AppOnboardingCompanyRouteImport } from './routes/app/onboarding/company'
import { Route as AppCompaniesNewRouteImport } from './routes/app/companies/new'
import { Route as AppCompaniesCompanyIdIndexRouteImport } from './routes/app/companies/$companyId/index'
import { Route as AppCompaniesCompanyIdSettingsRouteImport } from './routes/app/companies/$companyId/settings'
import { Route as AppCompaniesCompanyIdJobsIndexRouteImport } from './routes/app/companies/$companyId/jobs/index'
import { Route as AppCompaniesCompanyIdJobsNewRouteImport } from './routes/app/companies/$companyId/jobs/new'
import { Route as AppCompaniesCompanyIdJobsJobIdIndexRouteImport } from './routes/app/companies/$companyId/jobs/$jobId/index'
import { Route as AppCompaniesCompanyIdJobsJobIdEditRouteImport } from './routes/app/companies/$companyId/jobs/$jobId/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyGateRoute = AuthVerifyGateRouteImport.update({
  id: '/auth/verify-gate',
  path: '/auth/verify-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingCompanyRoute = AppOnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesNewRoute = AppCompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIdIndexRoute =
  AppCompaniesCompanyIdIndexRouteImport.update({
    id: '/companies/$companyId/',
    path: '/companies/$companyId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesCompanyIdSettingsRoute =
  AppCompaniesCompanyIdSettingsRouteImport.update({
    id: '/companies/$companyId/settings',
    path: '/companies/$companyId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesCompanyIdJobsIndexRoute =
  AppCompaniesCompanyIdJobsIndexRouteImport.update({
    id: '/companies/$companyId/jobs/',
    path: '/companies/$companyId/jobs/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesCompanyIdJobsNewRoute =
  AppCompaniesCompanyIdJobsNewRouteImport.update({
    id: '/companies/$companyId/jobs/new',
    path: '/companies/$companyId/jobs/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesCompanyIdJobsJobIdIndexRoute =
  AppCompaniesCompanyIdJobsJobIdIndexRouteImport.update({
    id: '/companies/$companyId/jobs/$jobId/',
    path: '/companies/$companyId/jobs/$jobId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesCompanyIdJobsJobIdEditRoute =
  AppCompaniesCompanyIdJobsJobIdEditRouteImport.update({
    id: '/companies/$companyId/jobs/$jobId/edit',
    path: '/companies/$companyId/jobs/$jobId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-gate': typeof AuthVerifyGateRoute
  '/app/': typeof AppIndexRoute
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/onboarding/company': typeof AppOnboardingCompanyRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/app/companies/$companyId/settings': typeof AppCompaniesCompanyIdSettingsRoute
  '/app/companies/$companyId/': typeof AppCompaniesCompanyIdIndexRoute
  '/app/companies/$companyId/jobs/new': typeof AppCompaniesCompanyIdJobsNewRoute
  '/app/companies/$companyId/jobs/': typeof AppCompaniesCompanyIdJobsIndexRoute
  '/app/companies/$companyId/jobs/$jobId/edit': typeof AppCompaniesCompanyIdJobsJobIdEditRoute
  '/app/companies/$companyId/jobs/$jobId/': typeof AppCompaniesCompanyIdJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-gate': typeof AuthVerifyGateRoute
  '/app': typeof AppIndexRoute
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/onboarding/company': typeof AppOnboardingCompanyRoute
  '/app/companies': typeof AppCompaniesIndexRoute
  '/app/companies/$companyId/settings': typeof AppCompaniesCompanyIdSettingsRoute
  '/app/companies/$companyId': typeof AppCompaniesCompanyIdIndexRoute
  '/app/companies/$companyId/jobs/new': typeof AppCompaniesCompanyIdJobsNewRoute
  '/app/companies/$companyId/jobs': typeof AppCompaniesCompanyIdJobsIndexRoute
  '/app/companies/$companyId/jobs/$jobId/edit': typeof AppCompaniesCompanyIdJobsJobIdEditRoute
  '/app/companies/$companyId/jobs/$jobId': typeof AppCompaniesCompanyIdJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-gate': typeof AuthVerifyGateRoute
  '/app/': typeof AppIndexRoute
  '/app/companies/new': typeof AppCompaniesNewRoute
  '/app/onboarding/company': typeof AppOnboardingCompanyRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/app/companies/$companyId/settings': typeof AppCompaniesCompanyIdSettingsRoute
  '/app/companies/$companyId/': typeof AppCompaniesCompanyIdIndexRoute
  '/app/companies/$companyId/jobs/new': typeof AppCompaniesCompanyIdJobsNewRoute
  '/app/companies/$companyId/jobs/': typeof AppCompaniesCompanyIdJobsIndexRoute
  '/app/companies/$companyId/jobs/$jobId/edit': typeof AppCompaniesCompanyIdJobsJobIdEditRoute
  '/app/companies/$companyId/jobs/$jobId/': typeof AppCompaniesCompanyIdJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-gate'
    | '/app/'
    | '/app/companies/new'
    | '/app/onboarding/company'
    | '/app/companies/'
    | '/app/companies/$companyId/settings'
    | '/app/companies/$companyId/'
    | '/app/companies/$companyId/jobs/new'
    | '/app/companies/$companyId/jobs/'
    | '/app/companies/$companyId/jobs/$jobId/edit'
    | '/app/companies/$companyId/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-gate'
    | '/app'
    | '/app/companies/new'
    | '/app/onboarding/company'
    | '/app/companies'
    | '/app/companies/$companyId/settings'
    | '/app/companies/$companyId'
    | '/app/companies/$companyId/jobs/new'
    | '/app/companies/$companyId/jobs'
    | '/app/companies/$companyId/jobs/$jobId/edit'
    | '/app/companies/$companyId/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-gate'
    | '/app/'
    | '/app/companies/new'
    | '/app/onboarding/company'
    | '/app/companies/'
    | '/app/companies/$companyId/settings'
    | '/app/companies/$companyId/'
    | '/app/companies/$companyId/jobs/new'
    | '/app/companies/$companyId/jobs/'
    | '/app/companies/$companyId/jobs/$jobId/edit'
    | '/app/companies/$companyId/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyGateRoute: typeof AuthVerifyGateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-gate': {
      id: '/auth/verify-gate'
      path: '/auth/verify-gate'
      fullPath: '/auth/verify-gate'
      preLoaderRoute: typeof AuthVerifyGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/companies/': {
      id: '/app/companies/'
      path: '/companies'
      fullPath: '/app/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding/company': {
      id: '/app/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/app/onboarding/company'
      preLoaderRoute: typeof AppOnboardingCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/new': {
      id: '/app/companies/new'
      path: '/companies/new'
      fullPath: '/app/companies/new'
      preLoaderRoute: typeof AppCompaniesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/': {
      id: '/app/companies/$companyId/'
      path: '/companies/$companyId'
      fullPath: '/app/companies/$companyId/'
      preLoaderRoute: typeof AppCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/settings': {
      id: '/app/companies/$companyId/settings'
      path: '/companies/$companyId/settings'
      fullPath: '/app/companies/$companyId/settings'
      preLoaderRoute: typeof AppCompaniesCompanyIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/jobs/': {
      id: '/app/companies/$companyId/jobs/'
      path: '/companies/$companyId/jobs'
      fullPath: '/app/companies/$companyId/jobs/'
      preLoaderRoute: typeof AppCompaniesCompanyIdJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/jobs/new': {
      id: '/app/companies/$companyId/jobs/new'
      path: '/companies/$companyId/jobs/new'
      fullPath: '/app/companies/$companyId/jobs/new'
      preLoaderRoute: typeof AppCompaniesCompanyIdJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/jobs/$jobId/': {
      id: '/app/companies/$companyId/jobs/$jobId/'
      path: '/companies/$companyId/jobs/$jobId'
      fullPath: '/app/companies/$companyId/jobs/$jobId/'
      preLoaderRoute: typeof AppCompaniesCompanyIdJobsJobIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$companyId/jobs/$jobId/edit': {
      id: '/app/companies/$companyId/jobs/$jobId/edit'
      path: '/companies/$companyId/jobs/$jobId/edit'
      fullPath: '/app/companies/$companyId/jobs/$jobId/edit'
      preLoaderRoute: typeof AppCompaniesCompanyIdJobsJobIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesNewRoute: typeof AppCompaniesNewRoute
  AppOnboardingCompanyRoute: typeof AppOnboardingCompanyRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppCompaniesCompanyIdSettingsRoute: typeof AppCompaniesCompanyIdSettingsRoute
  AppCompaniesCompanyIdIndexRoute: typeof AppCompaniesCompanyIdIndexRoute
  AppCompaniesCompanyIdJobsNewRoute: typeof AppCompaniesCompanyIdJobsNewRoute
  AppCompaniesCompanyIdJobsIndexRoute: typeof AppCompaniesCompanyIdJobsIndexRoute
  AppCompaniesCompanyIdJobsJobIdEditRoute: typeof AppCompaniesCompanyIdJobsJobIdEditRoute
  AppCompaniesCompanyIdJobsJobIdIndexRoute: typeof AppCompaniesCompanyIdJobsJobIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCompaniesNewRoute: AppCompaniesNewRoute,
  AppOnboardingCompanyRoute: AppOnboardingCompanyRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppCompaniesCompanyIdSettingsRoute: AppCompaniesCompanyIdSettingsRoute,
  AppCompaniesCompanyIdIndexRoute: AppCompaniesCompanyIdIndexRoute,
  AppCompaniesCompanyIdJobsNewRoute: AppCompaniesCompanyIdJobsNewRoute,
  AppCompaniesCompanyIdJobsIndexRoute: AppCompaniesCompanyIdJobsIndexRoute,
  AppCompaniesCompanyIdJobsJobIdEditRoute:
    AppCompaniesCompanyIdJobsJobIdEditRoute,
  AppCompaniesCompanyIdJobsJobIdIndexRoute:
    AppCompaniesCompanyIdJobsJobIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyGateRoute: AuthVerifyGateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
