export interface ValidationError {
  field: string;
  message: string;
  code?: string;
}

export interface ApiErrorResponse {
  statusCode: number;
  error: string;
  message: string;
  code?: string;
  details?: ValidationError[];
  timestamp: string;
  path: string;
}

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  REFRESH_REUSE_DETECTED = 'REFRESH_REUSE_DETECTED',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  PHONE_TAKEN = 'PHONE_TAKEN',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  INSUFFICIENT_COMPANY_ROLE = 'INSUFFICIENT_COMPANY_ROLE',
  NOT_COMPANY_MEMBER = 'NOT_COMPANY_MEMBER',
  LAST_OWNER_PROTECTION = 'LAST_OWNER_PROTECTION',
  WORKER_CANNOT_JOIN_COMPANY = 'WORKER_CANNOT_JOIN_COMPANY',
  LOCATION_HAS_SHIFTS = 'LOCATION_HAS_SHIFTS',
  COORDINATES_MUST_BE_PAIRED = 'COORDINATES_MUST_BE_PAIRED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  VERIFICATION_TOKEN_INVALID = 'VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',
  VERIFICATION_TOKEN_USED = 'VERIFICATION_TOKEN_USED',
  VERIFICATION_RESEND_COOLDOWN = 'VERIFICATION_RESEND_COOLDOWN',
  VERIFICATION_DAILY_LIMIT = 'VERIFICATION_DAILY_LIMIT',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
  PASSWORD_RESET_TOKEN_USED = 'PASSWORD_RESET_TOKEN_USED',
  PASSWORD_RESET_RATE_LIMITED = 'PASSWORD_RESET_RATE_LIMITED',
}
